##############################################################################
#   
#  Configuration for the MkDocs-base site.
#
#  This file is part of XAD, a comprehensive C++ library for
#  automatic differentiation.
#
#  Copyright (C) 2010-2024 Xcelerit Computing Ltd.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   
##############################################################################

# Project information
site_name:  "XAD Automatic Differentiation"
site_url: https://auto-differentiation.github.io
site_author: Xcelerit
site_description: >-
  Maximise your code efficiency with XAD, the leading library for automatic differentiation in various applications.


# Repository
repo_url: "https://github.com/auto-differentiation/xad/"
repo_name: xad

# Copyright in footer
copyright: >
  Copyright &copy; 2010-2024, Xcelerit Computing Limited

# Configuration
theme:
  name: material
  custom_dir: docs/.overrides
  logo: images/logo.svg
  palette:
    - scheme: default
      primary: grey
      media: "(prefers-color-scheme: light)" 
      accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: logo

  globaltoc_collapse: true
  features:
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    # - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
extra:
  generator: false
  version: !ENV [LATEST_VERSION, development]
plugins: 
  - search
  - social
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'aad.md': 'tutorials/aad.md'
        'tutorials.md': 'tutorials/aad.md'
        'examples/simple_examples.md': 'examples.md'
        'examples/quantlib.md': 'quantlib-risks/cxx.md'
        'quantlib.md': 'quantlib-risks/practical-guide.md'
        'quantlib-risks.md': 'quantlib-risks/practical-guide.md'
        'ref.md': 'ref/python.md'
        'getting_started.md': 'installation/python.md'
        'installation.md': 'installation/python.md'
        'tutorials/basic.md': 'tutorials/cxx.md#basic-usage'
        'tutorials/external_functions.md': 'tutorials/cxx.md#external-functions'
        'tutorials/checkpointing.md': 'tutorials/cxx.md#checkpointing'
        'tutorials/higher_order.md': 'tutorials/cxx.md#higher-order-derivatives'
        'python.md': 'installation/python.md'
        

markdown_extensions: 
  - abbr
  - admonition
  - def_list
  - toc:
      permalink: true
      title: Contents
      toc_depth: 4
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      #pygments_style: sphinx
  - pymdownx.superfences 
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.keys
  - meta

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js

extra_css:
  - custom.css

nav:
  - Home: README.md
  - Installation: 
    - Python: installation/python.md
    - C++: installation/cxx.md
    - Tested Platfoms: installation/platforms.md
  - Tutorials:
    - AD Background:  tutorials/aad.md
    - Python: tutorials/python.md
    - C++: tutorials/cxx.md  
    - Handling Discontinuities: tutorials/smoothed_math.md
  - Examples: examples.md
  - QuantLib-Risks:
    - Python: quantlib-risks/python.md 
    - C++: quantlib-risks/cxx.md
    - Practical Guide: quantlib-risks/practical-guide.md
  - Reference:
    - Python: ref/python.md
    - Headers and Namespaces: ref/headers.md
    - AD Mode Interface: ref/interface.md
    - Forward Mode Type FReal: ref/freal.md
    - Adjoint Mode Type AReal: ref/areal.md
    - Global Functions: ref/global.md
    - Mathematical Operations: ref/math.md
    - Complex: ref/complex.md
    - Smoothed Mathematical Functions: ref/smooth-math.md
    - Expressions: ref/expressions.md
    - Tape: ref/tape.md
    - CheckpointCallback: ref/chkpt_cb.md
    - Exceptions: ref/exceptions.md
    - Version Information: ref/version.md
  - FAQ: faq.md
  - About: about.md